### PR TITLE
Add setAutoBootOnLoad function.

### PR DESCRIPTION
**Pull request by lovyan03**
Refactoring Power.cpp

### CODE REVIEW

**Comment by lovyan03** [comment]
setAutoBootOnLoad's default value is true.

When the power is off, a voltage of about 1.9V is applied 5V-GND.
At this time, connecting a load (ex.CardKB) here automatically turns on the power.
[twitter movie](https://mobile.twitter.com/lovyan03/status/1105058712803135489)

After calling "setAutoBootOnLoad(false)", the potential difference drops to about 400mV and the power is not turned on even if the load is connected.

**Comment by nmori** [comment]
getI2CReg / setI2CReg has usefull other device as well. Suggest moving to M5stack.cpp

**Comment by zhouyangyale** [comment]
I see，Let me check it

**Comment by lovyan03** [comment]
If you move the class of the function,
I think... name is mismatch.
getI2CReg to readI2CByte
setI2CReg to writeI2CByte

**Comment by zhouyangyale** [comment]
ok，
For stability, don't move getI2CReg first。

**Pull request merged**
