### PR TITLE
Add some examples

### PR DESCRIPTION
**Pull request by Tinyu-Zhao**

### CODE REVIEW

**Comment by f4grx** [comment]
https://github.com/m5stack/M5Stack/issues/261

**Comment by lovyan03** [comment]
@Tinyu-Zhao 
Why do you keep committing pull requests before they are merged?
I'm very tired of getting a lot of useless notifications because of you.

image

Usually, after submitting a pull request, you should not make any other changes until it is merged.
You should work in separate branches.

**Comment by Tinyu-Zhao** [comment]
Sorry, I don’t know that this will cause a lot of emails to be sent, I will try to work in other branches

Tinyu Chiu
2021年9月3日 +0800 08:39 lovyan03 ***@***.***>，写道：

**Comment by lovyan03** [comment]
@Tinyu-Zhao 
When you submit a pull request, don't make any changes to the branch until it has been merged, rejected, or concluded in some other way.
A pull request should be submitted when the change work is complete and ready to be safely merged.
You should not submit a pull request from a branch you are working on.

**Comment by Tinyu-Zhao** [comment]
Thank you for your reminder, otherwise I might keep this wrong bad habit

Tinyu Chiu
2021年9月3日 +0800 08:48 lovyan03 ***@***.***>，写道：

**Pull request merged**
